version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#      - 27017:27017
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword

volumes:
  mongodb_data_container:



